[project]
name = 'Mobile-Car-Detail-Service-Insurance'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.car-detail-claims]
path = 'contracts/car-detail-claims.clar'
clarity_version = 3
epoch = 'latest'

[contracts.detailing-service-oracle]
path = 'contracts/detailing-service-oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.vehicle-condition-tracker]
path = 'contracts/vehicle-condition-tracker.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
